routes/web.php
<?php

use App\Models\TrialRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Validator;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', function () {
    return view('frontend.pages.home');
})->name('home');

Route::get('/about', function () {
    return view('frontend.pages.about');
})->name('about');

Route::get('/features', function () {
    return view('frontend.pages.features');
})->name('features');

Route::get('/pricing', function () {
    return view('frontend.pages.pricing');
})->name('pricing');

Route::get('/contact', function () {
    return view('frontend.pages.contact');
})->name('contact');

Route::get('/book-a-trail', function () {
    return view('frontend.pages.trial');
})->name('trial');

Route::post('/book-trail', function (Request $request) {
    //
    $validator = Validator::make($request->all(),[
        'name'    => 'required',
        'phone'   => 'required',
        'email'   => 'required',
    ]);

    if($validator->fails()){
        return redirect()->back()->withErrors($validator)->withInput();
    }

    TrialRequest::create([
        'name' => $request->name,
        'email' => $request->email,
        'phone' => $request->phone,
    ]);

    return redirect()->back()->with('success','Thankyou showing Intrest in our free Trial. Our representive will call you back to assit with your trial.');
})->name('trial.book');

app/Models/LeadProfile.php
<?php

namespace App\Models;

use Auth;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LeadProfile extends Model
{
    use HasFactory;
    
    protected  $primaryKey = 'lead_id';

    public $fillable = [
        'name','phone','alt_phone','email','dob','address','city','state','country','tags'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'dob' => 'date',
        
    ];

    /**
     *  Setup model event hooks
     */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            //
            $model->ucid         = Auth::user()->ucid;
            $model->created_by   = Auth::user()->id;
        });
    }

    public function getFullAddressAttribute(){
        return ucwords("{$this->address}, {$this->city}, {$this->state} - {$this->country}");
    }

    public function getFullNameAttribute($value)
    {
        return ucwords("{$this->name}");
    }
    
}

app/Models/UserProfile.php
<?php

namespace App\Models;

use Auth;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserProfile extends Model
{
    use HasFactory;
    protected $table = 'profiles';

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'dob' => 'date',
        
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'uid',
        'ucid',
        'plan_id',
        'plan_duration',
        'plan_expiry',
        'email',
        'avatar',
        'display_name',
        'company_name',
        'company_logo',
        'first_name',
        'last_name' ,
        'phone',
        'website',
        'address',
        'city',
        'state',
        'country',
        'status',        
    ];

    /**
     *  Setup model event hooks
    */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            //
            if(Auth::guard('web')->check()){
                $model->ucid = Auth::user()->ucid;
            }
        });
    }

    public function getFullAddressAttribute(){
        return ucwords("{$this->address}, {$this->city}, {$this->state} - {$this->country}");
    }

    public function getFullNameAttribute(){
        return ucwords("{$this->first_name} {$this->last_name}");
    }

    public function getAssetAvatarAttribute(){
        return asset('assets/avatars').'/'.$this->avatar;
    }

    public function getAssetLogoAttribute(){
        return asset('assets/logos').'/'.$this->company_logo;
    }

    public function getShortNameAttribute(){
        $last = substr($this->last_name,0, 1);
        return ucwords("{$this->first_name} {$last}.");
    }
    
    public function scopeCompanyEmployees($query){
        return $query->where('ucid', Auth::user()->ucid);//->whereNotIn('uid',[Auth::user()->id]);
    }

    public function user(){
        return $this->hasOne('App\Models\User','id','uid');
    }

    public function plan(){
        return $this->hasOne('App\Models\Plans','id','plan_id');
    }

}

app/Http/Controllers/Backend/AppController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;


class AppController extends Controller
{
    //
    public function index(){
        //
        return redirect()->route('dashboard');
    }

    public function dashboard(){
        //
        return view('backend.pages.dashboard');
    }

    public function admin(){
        //
        return view('backend.pages.admin');
    }
}

app/Http/Controllers/Backend/CalendarController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CalendarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('backend.pages.calendar.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ClientsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Clients;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ClientsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
    */
    public function __construct()
    {
        $this->middleware(['role:admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $clients  = Clients::companyClients()->get();
        return view('backend.pages.clients.index',compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('backend.pages.clients.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(),[
            'name'    => 'required',
            'phone'   => 'required',
            'dob'     => 'required',
            'address' => 'required',
            'country' => 'required',
            'state'   => 'required',
            'city'    => 'required',
        ]);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $request['dob'] = date('Y-m-d',strtotime($request->dob));
        Clients::create($request->all());
        return redirect()->route('clients.index')->with('success','New Client created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $client = Clients::find($id);
        return view('backend.pages.clients.edit',compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $validator = Validator::make($request->all(),[
            'name'    => 'required',
            'phone'   => 'required',
            'dob'     => 'required',
            'address' => 'required',
            'country' => 'required',
            'state'   => 'required',
            'city'    => 'required',
        ]);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $request['dob'] = date('Y-m-d',strtotime($request->dob));
        Clients::find($id)->update($request->all());
        return redirect()->route('clients.index')->with('success','Client info Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/FilterController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Leads;
use Carbon\Carbon;
use Auth;

class FilterController extends Controller
{
    //
    public function filter($type, $role = 'admin'){
        //
        if($role == 'admin'){
            //
            if($type == 'leads'){
                //
                $today = Leads::companyLeads()->where('status',1)->whereDate('created_at', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->whereIn('status',[1,2,3,4])->get();
            }
            if($type == 'followup'){
                $today = Leads::companyLeads()->where('status',1)->whereDate('next_followup', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('status',1)->whereDate('next_followup','<',Carbon::today()->format('Y-m-d'))->get();
            }
    
            if($type == 'converted'){
                $today = Leads::companyLeads()->where('status',2)->whereDate('next_followup', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('status',2)->whereMonth('next_followup',Carbon::today()->format('n'))->get();
            }
    
            if($type == 'walkin'){
                $today = Leads::companyLeads()->where('status',1)->where('followup_type','walkin')->whereDate('generated_at', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('status',1)->where('followup_type','walkin')->whereMonth('generated_at',Carbon::today()->format('n'))->get();
            }
    
            if($type == 'payment'){
                $today = Leads::companyLeads()->where('status',2)->whereDate('converted_at', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('status',2)->whereMonth('converted_at',Carbon::today()->format('n'))->get();
            }
        }else{
            if($type == 'leads'){
                //
                $today = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->whereIn('status',[1,2,3])->get();
                $month = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',4)->get();
            }
            if($type == 'followup'){
                $today = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',1)->whereDate('next_followup', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',1)->whereDate('next_followup','<',Carbon::today()->format('Y-m-d'))->get();
            }
    
            if($type == 'converted'){
                $today = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',2)->whereDate('converted_at', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',2)->whereMonth('converted_at',Carbon::today()->format('n'))->get();
            }
    
            if($type == 'walkin'){
                $today = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',1)->where('followup_type','walkin')->whereDate('generated_at', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',1)->where('followup_type','walkin')->whereMonth('generated_at',Carbon::today()->format('n'))->get();
            }
    
            if($type == 'payment'){
                $today = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',2)->whereDate('converted_at', Carbon::today()->format('Y-m-d'))->get();
                $month = Leads::companyLeads()->where('agent_id',Auth::user()->profile->id)->where('status',2)->whereMonth('converted_at',Carbon::today()->format('n'))->get();
            }
            
        }

        return view('backend.pages.filter.index',[
            'today' => $today,
            'month' => $month,
            'type'  => $type,
        ]);
    }
}

app/Http/Controllers/Backend/MessageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Messages;
use App\Models\UserProfile;
use Auth;
use Illuminate\Http\Request;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $inbox = Messages::where('sent_to',Auth::user()->profile->id)->orderBy('created_at','DESC')->get();
        $sent  = Messages::where('sent_by',Auth::user()->profile->id)->orderBy('created_at','DESC')->get();
        return view('backend.pages.message.index',compact('inbox','sent'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id = null)
    {
        //
        $agents  =  UserProfile::companyEmployees()->get();
        return view('backend.pages.message.new',compact('agents','id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function send(Request $request)
    {
        //
        $this->validate($request,[
            'agent_id' => 'required',
            'subject'  => 'required',
            'message'  => 'required',
        ]);
        
        $request['sent_by']   = Auth::user()->profile->id;
        $request['sent_to']   = $request->agent_id;
        $message = Messages::create($request->all());
        return redirect()->route('dashboard')->with('success','Message Sent');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $message = Messages::find($id);
        $message->update([
            'is_read' => 1,
        ]);
        return view('pages.message.show',compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/inc/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                2019-{{ date('Y') }} © Curvet.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right d-none d-sm-block">
                    Crafted with <i class="uil uil-heart text-danger"></i> by <a href="https://overleap.co.in/" target="_blank" class="text-reset">Overleap</a>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/backend/inc/header.blade.php
<div class="navbar-header">
    <div class="d-flex">
        <!-- LOGO -->
        <div class="navbar-brand-box">
            <a href="{{ route('dashboard') }}" class="logo logo-dark">
                <span class="logo-sm">
                    <img src="{{ asset('web/media/bdm.png') }}" alt="" height="26">
                </span>
                <span class="logo-lg">
                    <img src="{{ asset('web/media/bdm.png') }}" alt="" height="20">
                </span>
            </a>

            <a href="{{ route('dashboard') }}" class="logo logo-light">
                <span class="logo-sm">
                    <img src="{{ asset('web/media/bdm.png') }}" alt="" height="26">
                </span>
                <span class="logo-lg">
                    <img src="{{ asset('web/media/bdm.png') }}" alt="" height="20">
                </span>
            </a>
        </div>

        <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light" data-toggle="collapse" data-target="#topnav-menu-content">
            <i class="uil uil-bars"></i>
        </button>

        <!-- App Search-->
        <form class="app-search d-none d-lg-block">
            <div class="position-relative">
                <input type="text" class="form-control" placeholder="Search...">
                <span class="uil-search"></span>
            </div>
        </form>
    </div>

    <div class="d-flex">

        <div class="dropdown d-inline-block d-lg-none ml-2">
            <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="uil-search"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                aria-labelledby="page-header-search-dropdown">
    
                <form class="p-3">
                    <div class="form-group m-0">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="dropdown d-none d-lg-inline-block ml-1">
            <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                <i class="uil-minus-path"></i>
            </button>
        </div>

        {{-- <div class="dropdown d-inline-block" >
            <button type="button" class="btn header-item noti-icon waves-effect dropdown-toggle" id="page-header-notifications-dropdown"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="uil-bell"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                aria-labelledby="page-header-notifications-dropdown">
                <div class="p-3">
                    <div class="row align-items-center">
                        <div class="col">
                            <h5 class="m-0 font-size-16"> Notifications </h5>
                        </div>
                        <div class="col-auto">
                            <a href="#!" class="small"> Mark all as read</a>
                        </div>
                    </div>
                </div>
                <div data-simplebar style="max-height: 230px;">
                    <a href="#" class="text-reset notification-item">
                        <div class="media">
                            <div class="avatar-xs mr-3">
                                <span class="avatar-title bg-primary rounded-circle font-size-16">
                                    <i class="uil-shopping-basket"></i>
                                </span>
                            </div>
                            <div class="media-body">
                                <h6 class="mt-0 mb-1">Your order is placed</h6>
                                <div class="font-size-12 text-muted">
                                    <p class="mb-1">If several languages coalesce the grammar</p>
                                    <p class="mb-0"><i class="mdi mdi-clock-outline"></i> 3 min ago</p>
                                </div>
                            </div>
                        </div>
                    </a>
                    <a href="#" class="text-reset notification-item">
                        <div class="media">
                            <img src="{{ asset('assets/images/users/avatar-3.jpg') }}"
                                class="mr-3 rounded-circle avatar-xs" alt="user-pic">
                            <div class="media-body">
                                <h6 class="mt-0 mb-1">James Lemire</h6>
                                <div class="font-size-12 text-muted">
                                    <p class="mb-1">It will seem like simplified English.</p>
                                    <p class="mb-0"><i class="mdi mdi-clock-outline"></i> 1 hours ago</p>
                                </div>
                            </div>
                        </div>
                    </a>
                    <a href="#" class="text-reset notification-item">
                        <div class="media">
                            <div class="avatar-xs mr-3">
                                <span class="avatar-title bg-success rounded-circle font-size-16">
                                    <i class="uil-truck"></i>
                                </span>
                            </div>
                            <div class="media-body">
                                <h6 class="mt-0 mb-1">Your item is shipped</h6>
                                <div class="font-size-12 text-muted">
                                    <p class="mb-1">If several languages coalesce the grammar</p>
                                    <p class="mb-0"><i class="mdi mdi-clock-outline"></i> 3 min ago</p>
                                </div>
                            </div>
                        </div>
                    </a>

                    <a href="#" class="text-reset notification-item">
                        <div class="media">
                            <img src="{{ asset('assets/images/users/avatar-4.jpg') }}"
                                class="mr-3 rounded-circle avatar-xs" alt="user-pic">
                            <div class="media-body">
                                <h6 class="mt-0 mb-1">Salena Layfield</h6>
                                <div class="font-size-12 text-muted">
                                    <p class="mb-1">As a skeptical Cambridge friend of mine occidental.</p>
                                    <p class="mb-0"><i class="mdi mdi-clock-outline"></i> 1 hours ago</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="p-2 border-top">
                    <a class="btn btn-sm btn-link font-size-14 btn-block text-center" href="javascript:void(0)">
                        <i class="uil-arrow-circle-right mr-1"></i> View More..
                    </a>
                </div>
            </div>
        </div> --}}
        @auth('web')
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect dropdown-toggle" id="page-header-user-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @if(Auth::user()->profile->avatar === 'default')
                        <img class="rounded-circle header-profile-user" src="{{ Avatar::create(Auth::user()->profile->full_name)->toBase64() }}" alt="Header Avatar">
                    @else
                        <img class="rounded-circle header-profile-user" src="{{ asset('assets/images/users/avatar-4.jpg') }}" alt="Header Avatar">
                    @endif
                    <span class="d-none d-xl-inline-block ml-1 font-weight-medium font-size-15">{{ Auth::user()->profile->short_name }}</span>
                    <i class="uil-angle-down d-none d-xl-inline-block font-size-15"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" data-turbolink="false">
                    <!-- item-->
                    <a class="dropdown-item" href="{{ route('profile.view',Auth::user()->profile->id) }}"><i class="uil uil-user-circle font-size-18 align-middle text-muted mr-1"></i> <span class="align-middle">My Account</span></a>
                    <a class="dropdown-item" href="#"><i class="uil uil-lock-alt font-size-18 align-middle mr-1 text-muted"></i> <span class="align-middle">Lock screen</span></a>
                    <a class="dropdown-item" href="{{ route('account.logout') }}"><i class="uil uil-sign-out-alt font-size-18 align-middle mr-1 text-muted"></i> <span class="align-middle">Sign out</span></a>
                </div>
            </div>
        @endauth

        @auth('master')
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect dropdown-toggle" id="page-header-user-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="rounded-circle header-profile-user" src="{{ Avatar::create(Auth::user()->name)->toBase64() }}" alt="Header Avatar">                    
                    <span class="d-none d-xl-inline-block ml-1 font-weight-medium font-size-15">{{ ucwords(Auth::user()->name) }}</span>
                    <i class="uil-angle-down d-none d-xl-inline-block font-size-15"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" data-turbolink="false">
                    <!-- item-->                    
                    <a class="dropdown-item" href="{{ route('master.logout') }}"><i class="uil uil-sign-out-alt font-size-18 align-middle mr-1 text-muted"></i> <span class="align-middle">Sign out</span></a>
                </div>
            </div>
        @endauth

    </div>
</div>

resources/views/backend/inc/modal.blade.php
<!-- MODAL -->
<div id="modal-view" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        </div>
      </div>
    </div>
  </div>
  <!-- modal -->
  