routes/web.php
<?php

use App\Models\TrialRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Validator;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', function () {
    return view('frontend.pages.home');
})->name('home');

Route::get('/about', function () {
    return view('frontend.pages.about');
})->name('about');

Route::get('/features', function () {
    return view('frontend.pages.features');
})->name('features');

Route::get('/pricing', function () {
    return view('frontend.pages.pricing');
})->name('pricing');

Route::get('/contact', function () {
    return view('frontend.pages.contact');
})->name('contact');

Route::get('/book-a-trail', function () {
    return view('frontend.pages.trial');
})->name('trial');

Route::post('/book-trail', function (Request $request) {
    //
    $validator = Validator::make($request->all(),[
        'name'    => 'required',
        'phone'   => 'required',
        'email'   => 'required',
    ]);

    if($validator->fails()){
        return redirect()->back()->withErrors($validator)->withInput();
    }

    TrialRequest::create([
        'name' => $request->name,
        'email' => $request->email,
        'phone' => $request->phone,
    ]);

    return redirect()->back()->with('success','Thankyou showing Intrest in our free Trial. Our representive will call you back to assit with your trial.');
})->name('trial.book');

app/Models/LeadProfile.php
<?php

namespace App\Models;

use Auth;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LeadProfile extends Model
{
    use HasFactory;
    
    protected  $primaryKey = 'lead_id';

    public $fillable = [
        'name','phone','alt_phone','email','dob','address','city','state','country','tags'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'dob' => 'date',
        
    ];

    /**
     *  Setup model event hooks
     */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            //
            $model->ucid         = Auth::user()->ucid;
            $model->created_by   = Auth::user()->id;
        });
    }

    public function getFullAddressAttribute(){
        return ucwords("{$this->address}, {$this->city}, {$this->state} - {$this->country}");
    }

    public function getFullNameAttribute($value)
    {
        return ucwords("{$this->name}");
    }
    
}

app/Models/UserProfile.php
<?php

namespace App\Models;

use Auth;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserProfile extends Model
{
    use HasFactory;
    protected $table = 'profiles';

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'dob' => 'date',
        
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'uid',
        'ucid',
        'plan_id',
        'plan_duration',
        'plan_expiry',
        'email',
        'avatar',
        'display_name',
        'company_name',
        'company_logo',
        'first_name',
        'last_name' ,
        'phone',
        'website',
        'address',
        'city',
        'state',
        'country',
        'status',        
    ];

    /**
     *  Setup model event hooks
    */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            //
            if(Auth::guard('web')->check()){
                $model->ucid = Auth::user()->ucid;
            }
        });
    }

    public function getFullAddressAttribute(){
        return ucwords("{$this->address}, {$this->city}, {$this->state} - {$this->country}");
    }

    public function getFullNameAttribute(){
        return ucwords("{$this->first_name} {$this->last_name}");
    }

    public function getAssetAvatarAttribute(){
        return asset('assets/avatars').'/'.$this->avatar;
    }

    public function getAssetLogoAttribute(){
        return asset('assets/logos').'/'.$this->company_logo;
    }

    public function getShortNameAttribute(){
        $last = substr($this->last_name,0, 1);
        return ucwords("{$this->first_name} {$last}.");
    }
    
    public function scopeCompanyEmployees($query){
        return $query->where('ucid', Auth::user()->ucid);//->whereNotIn('uid',[Auth::user()->id]);
    }

    public function user(){
        return $this->hasOne('App\Models\User','id','uid');
    }

    public function plan(){
        return $this->hasOne('App\Models\Plans','id','plan_id');
    }

}

resources/views/backend/pages/employee/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Employee')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">

            <div class="card-body">
                <x-validation />
                <!-- Card Body -->
                <form name="profileForm" method="post" action="{{ route('employee.update', $employee->id ) }}"
                    enctype="multipart/form-data" data-parsley-validate>
                    @csrf
                    @method('patch')
                    <div class="form-layout">
                        <div class="row mg-b-25">

                            <div class="col-lg-2 text-center">
                                @if($employee->avatar === 'default')
                                <img src="{{ Avatar::create($employee->full_name)->toBase64() }}" class="img-thumbnail rounded-circle avatar-xl" />
                                @else
                                    <img src="{{ $employee->asset_avatar }}" class="img-thumbnail rounded-circle avatar-xl" />
                                @endif
                            </div>

                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="form-control-label">Update Profile Picture:</label>
                                    <input class="form-control" type="file" name="user_img" value="">
                                </div>
                            </div>

                            <div class="col-md-12">
                                <hr>
                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label">Email: <span class="text-danger">*</span></label>
                                    <input class="form-control" type="email" name="email" value="{{ $employee->email }}"
                                        placeholder="Enter Email/Username" required>
                                </div>
                            </div>
                            <div class="col-lg-6">&nbsp;</div>


                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="form-control-label">Firstname: <span
                                            class="text-danger">*</span></label>
                                    <input class="form-control" type="text" name="first_name"
                                        style="text-transform:capitalize" value="{{ $employee->first_name }}"
                                        minlength="3" placeholder="Enter firstname" required>
                                </div>
                            </div>

                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="form-control-label">Lastname:</label>
                                    <input class="form-control" type="text" name="last_name"
                                        style="text-transform:capitalize" value="{{ $employee->last_name }}"
                                        placeholder="Enter lastname" required>
                                </div>
                            </div>

                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="form-control-label">Mobile Number: <span
                                            class="text-danger">*</span></label>
                                    <input class="form-control" type="phone" name="phone" value="{{ $employee->phone }}"
                                        minlength="10" maxlength="13" placeholder="Enter Mobile Number" required>
                                </div>
                            </div>

                            <div class="col-lg-3">
                                <div id="slWrapperBirth" class="parsley-select">
                                    <div class="form-group">
                                        <label class="form-control-label">Date of Birth: <span
                                            class="text-danger">*</span></label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="uil uil-schedule tx-16 lh-0 op-6"></i>
                                                </div>
                                            </div>
                                            <input type="text" data-parsley-class-handler="#slWrapperBirth"
                                                data-parsley-errors-container="#slErrorContainerBirth"
                                                class="form-control fc-dobpicker" value="{{ date('d-m-Y',strtotime($employee->dob)) }}" name="dob"
                                                placeholder="Date of Birth" autocomplete="off">
                                        </div><!-- wd-200 -->
                                        <div id="slErrorContainerBirth"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-control-label">Address:</label>
                                    <textarea class="form-control" name="address"
                                        placeholder="Enter Address">{{ $employee->address }}</textarea>
                                </div>
                            </div>

                            <x-locations :model="$employee" />

                        </div><!-- row -->

                        <div class="form-layout-footer">
                            <button type="submit" class="btn btn-primary bd-0">Update Profile</button>
                        </div><!-- form-layout-footer -->
                        <hr>
                    </div><!-- form-layout -->
                </form>

                <h2>Update Credentials</h2>
                <hr>
                <form name="updatePassword" method="POST"
                    action="{{ route('profile.employee.password',$employee->uid) }}" data-parsley-validate>
                    @csrf
                    <div class="form-layout">
                        <div class="row mg-b-25">

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label">Email/Username:</label>
                                    <input class="form-control" type="email" name="email"
                                        value="{{ $employee->user->email }}" readonly required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                &nbsp;
                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label">Password:</label>
                                    <input class="form-control" type="password" name="password"
                                        placeholder="Enter New Password" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label">Repeat Password:</label>
                                    <input class="form-control" type="password" name="password_confirmation"
                                        placeholder="Repeat Password" required>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div id="slWrapperStatus" class="parsley-select">
                                    <div class="form-group">
                                        <label class="form-control-label">Profile Status: <span
                                                class="tx-danger">*</span></label>
                                        <select class="form-control select2" name="status"
                                            data-parsley-class-handler="#slWrapperStatus"
                                            data-parsley-errors-container="#slErrorContainerStatus" required>
                                            <option value="1" @if($employee->user->status =='1') selected @endif>Active
                                            </option>
                                            <option value="0" @if($employee->user->status =='0') selected @endif>Suspend
                                            </option>
                                        </select>
                                        <div id="slErrorContainerStatus"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <hr>
                                <div class="form-group">
                                    <label class="form-control-label">Permissions: </label>
                                </div>
                                
                                @foreach ($permissions as $key => $permission)
                                    <div class="form-group">
                                        <div class="custom-control custom-switch custom-switch-lg mb-10" dir="ltr">
                                            <input type="checkbox" class="custom-control-input" name="permissions[]" value="{{ $permission->name }}"
                                                @if(in_array($permission->name,Arr::flatten($employee->user->getPermissionNames())))
                                                    checked
                                                @endif
                                                id="permissionSwitch{{ $key }}">
                                            <label class="custom-control-label" for="permissionSwitch{{ $key }}">{{ ucwords($permission->name) }}</label>
                                        </div>
                                    </div>
                                @endforeach
                        </div>
                        <div class="form-group">
                            <hr>
                            <button type="submit" class="btn btn-danger bd-0">Update Credentials</button>
                        </div><!-- form-layout-footer -->
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
    <script>
        $('.fc-dobpicker').datetimepicker({
            timepicker: false,
            format:'d-m-Y',
            formatDate:'Y-m-d',
            formatTime:'H:i',
            maxDate:'{{ date("Y/m/d") }}',
        });

        $('.select2').select2();
    </script>
@endpush

resources/views/backend/pages/employee/index.blade.php
@extends('layouts.app')
@section('title', 'Employees List')
@section('turbolink','no-cache')
@section('content')
<div class="row">
    <div class="col"></div>
    @if(Auth::user()->profile->plan->users_limit == $employees->count())
        <div class="col">
            <div class="alert alert-solid alert-danger" role="alert">
                <strong>Users Limit {{ $employees->count()-1 }} of {{ Auth::user()->profile->plan->users_limit }} Reached. Please upgrade your account.</strong>
            </div><!-- alert -->
        </div>
    @else
        <div class="col-md-2">
            <div class="alert alert-solid alert-success" role="alert">
                <strong>Your Plan Users Limit {{ $employees->count()-1 }} of {{ Auth::user()->profile->plan->users_limit }}</strong>
            </div><!-- alert -->
        </div>
        <div class="col-md-2">
            <a href="{{ route('employee.create') }}" class="btn btn-success btn-rounded waves-effect waves-light mb-3 float-right">
                <i class="uil uil-plus-circle me-1"></i> Add New Employee
            </a>
        </div>
    @endif
</div>

<div class="row">
    <div class="col-12">
        <div class="table-wrapper">
            <table id="datatable"
                class="table table-centered table-hover datatable dt-responsive nowrap table-card-list"
                style="border-collapse: collapse; border-spacing: 0 12px; width: 100%;">
                <thead>
                    <tr class="bg-transparent">
                        <th class="wd-15p">Name</th>
                        <th class="wd-10p">Phone</th>
                        <th class="wd-10p">Email</th>
                        <th class="wd-15p">Created On</th>
                        <th class="wd-10p">Status</th>
                        <th class="wd-20p">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if(isset($employees) && $employees->isNotEmpty())
                    @foreach($employees as $key => $employee)
                        @if($employee->user->hasRole('agent'))
                        <tr>
                            <td>
                                {{-- <img src="{{ $employee->asset_avatar }}" class="avatar-sm align-self-center
                                rounded-circle" /> --}}
                                <div class="d-flex align-items-center">
                                    <div>
                                        @if($employee->avatar === 'default')
                                            <img src="{{ Avatar::create($employee->full_name)->toBase64() }}" class="img-thumbnail avatar-sm align-self-center rounded-circle mr-1" />
                                        @else
                                            <img src="{{ $employee->asset_avatar }}" class="img-thumbnail avatar-sm align-self-center rounded-circle mr-1" />
                                        @endif
                                    </div>
                                    <div class="">
                                        <p class="font-weight-bold mb-0">{{ $employee->full_name }}</p>
                                        <p class="text-muted mb-0">Agent</p>
                                    </div>
                                </div>
                            </td>
                            <td>{{ $employee->phone }}</td>
                            <td style="text-transform: lowercase !important">{{ $employee->email }}</td>
                            <td>
                                <a href="#">
                                    {{ \Carbon\Carbon::parse($employee->created_at)->diffForHumans() }}
                                    on
                                    {{ date('h:i A', strtotime($employee->created_at))}}
                                </a>
                            </td>
                            <td>
                                @if($employee->user->status == 1)
                                    <span class="btn btn-success btn-sm">Active</span>
                                @else
                                    <span class="btn btn-danger btn-sm">Suspended</span>
                                @endif
                            </td>
                            <td>
                                <a href="{{ route('employee.edit', $employee->id ) }}" class="btn text-primary"
                                    data-toggle="tooltip" data-placement="bottom" title="Edit Details"><i
                                        class="uil uil-edit-alt"></i>
                                </a>
                                @role('admin')
                                <a href="#" class="btn text-danger" data-toggle="tooltip" data-placement="bottom"
                                    title="Delete User"><i class="uil uil-trash-alt"></i></a>
                                @endrole
                            </td>
                        @endif
                        @endforeach
                        @endif
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable({
                retrieve: true,
                'columnDefs': [ {
                    'targets'  : [1,2,3,5], /* column index */
                    'orderable': false, /* true or false */
                }],
            });
        });
    </script>
@endpush

resources/views/backend/pages/employee/show.blade.php
@extends('app.layout.module')
@section('title', 'View Employee')
@section('content')
<div class="row">
<div class="col-md-12">
    <div class="card">
        <div class="card-header bg-primary d-flex align-items-center justify-content-between pd-y-5 bd-b">
            <h6 class="mg-b-0 tx-20 tx-white"><a href="{{ route('employee.index') }}" style="color:white"><i class="fa fa-arrow-left"></i></a> Employee</h6>
            <div class="card-option tx-24">
                <a href="" class="tx-white-8 hover-white mg-l-10"><i class="icon ion-android-more-vertical lh-0"></i></a>
            </div>
        </div>
        <div class="card-body">
         
                <div class="table-wrapper">
                        <table id="datatable" class="table display responsive nowrap">
                          <tbody>
                            <tr>
                                <th class="wd-15p">Date Joined</th> <td>{{ date('d, M Y', strtotime($emp->joining_date)) }}</td>
                            </tr>
                            <tr>
                                <th class="wd-15p">Salary</th> <td> ₹{{ $emp->salary }}</td>
                            </tr>
                            <tr>
                                <th class="wd-15p">Username/Email</th> <td>{{ $emp->users->email }}</td>
                            </tr>
                            <tr>
                              <th class="wd-15p">Name</th>  <td>{{ ucwords($emp->full_name) }}</td>
                            </tr>
                            <tr>
                              <th class="wd-20p">Phone Number</th>  <td>{{ $emp->phone_number }}</td>
                            </tr>
                            <tr>
                              <th class="wd-20p">Address</th>  <td>{{ $emp->address }}</td>
                            </tr>
                            <tr>
                              <th class="wd-20p">City</th>  <td>{{ ucwords($emp->city) }}</td>
                            </tr>
                            <tr>
                                <th class="wd-20p">State</th>  <td>{{ ucwords($emp->state) }}</td>
                            </tr>
                            <tr>
                                <th class="wd-20p">Country</th>  <td>{{ ucwords($emp->country) }}</td>
                            </tr>
                            
                          </tbody>
                         
                        </table>
                </div>

        
        </div>
    </div>
</div>
</div>

              <div class="card-body">

                <table class="table user-view-table m-0">
                  <tbody>
                    <tr>
                      <td>Username:</td>
                      <td>nmaxwell</td>
                    </tr>
                    <tr>
                      <td>Name:</td>
                      <td>Nelle Maxwell</td>
                    </tr>
                    <tr>
                      <td>E-mail:</td>
                      <td>nmaxwell@mail.com</td>
                    </tr>
                    <tr>
                      <td>Company:</td>
                      <td>Company Ltd.</td>
                    </tr>
                  </tbody>
                </table>

                <h6 class="mt-4 mb-3">Social links</h6>

                <table class="table user-view-table m-0">
                  <tbody>
                    <tr>
                      <td>Twitter:</td>
                      <td><a href="javascript:void(0)">https://twitter.com/user</a></td>
                    </tr>
                    <tr>
                      <td>Facebook:</td>
                      <td><a href="javascript:void(0)">https://www.facebook.com/user</a></td>
                    </tr>
                    <tr>
                      <td>Instagram:</td>
                      <td><a href="javascript:void(0)">https://www.instagram.com/user</a></td>
                    </tr>
                  </tbody>
                </table>

                <h6 class="mt-4 mb-3">Personal info</h6>

                <table class="table user-view-table m-0">
                  <tbody>
                    <tr>
                      <td>Birthday:</td>
                      <td>May 3, 1995</td>
                    </tr>
                    <tr>
                      <td>Country:</td>
                      <td>Canada</td>
                    </tr>
                    <tr>
                      <td>Languages:</td>
                      <td>English</td>
                    </tr>
                  </tbody>
                </table>

                <h6 class="mt-4 mb-3">Contacts</h6>

                <table class="table user-view-table m-0">
                  <tbody>
                    <tr>
                      <td>Phone:</td>
                      <td>+0 (123) 456 7891</td>
                    </tr>
                  </tbody>
                </table>

                <h6 class="mt-4 mb-3">Interests</h6>

                <table class="table user-view-table m-0">
                  <tbody>
                    <tr>
                      <td>Favorite music:</td>
                      <td>
                        Rock,
                        Alternative,
                        Electro,
                        Drum &amp; Bass,
                        Dance
                      </td>
                    </tr>
                    <tr>
                      <td>Favorite movies:</td>
                      <td>
                        The Green Mile,
                        Pulp Fiction,
                        Back to the Future,
                        WALL·E,
                        Django Unchained,
                        The Truman Show,
                        Home Alone,
                        Seven Pounds
                      </td>
                    </tr>
                  </tbody>
                </table>

              </div>
@endsection